version: '2'
.catalog:
  name: Gravitee.io Gateway
  version: Version 1.13.2
  description: "Gravitee.io Gateway"
  questions:
    - variable: environment_prefix
      label: "Environment prefix"
      description: |
        This is the prefix used for consul as 'qualification/white'
      default: "qualification/hmbu"
      required: true
      type: string
    - variable: consul_uri
      label: "Consul URI"
      description: |
        The consul URI for key/value management of environment variable
      default: "consul.consul.rancher.internal:8500"
      required: true
      type: string
    - variable: mongos_enable
      label: "Enable mongos cli ? (true|false)"
      description: |
        Does the mongos component should be launched ?
      required: false
      default: true
      type: boolean
    - variable: dc
      label: "Target Datacenter"
      description: |
        a = Z2, b = Y1, c = X1, d = F1, e = G1
      required: false
      default: a
      type: string
    - variable: tenant
      label: "Tenant"
      description: |
        Tenant
      required: false
      default: null
      type: string
    - variable: sharding_tags
      label: "Sharding Tags"
      description: |
        Sharding tags list
      required: false
      default: null
      type: string
services:
  webapp:
    scale: 1
    start_on_create: true
