name: Gravitee management API + UI + Mongos
description: |
  Gravitee management API + Gravitee UI + Mongos router 
version: 1.0.0
category: API management
maintainer: Olivier Lehouck <olivier.lehouck@adeo.com>
projectURL: 
