[template]
src = "gravitee.yml.tmpl"
dest = "/opt/graviteeio-management-api-1.13.2/config/gravitee.yml"
keys = [
"/graviteeio/apim/gateway/management/datasource/config/type",
"/graviteeio/apim/gateway/management/datasource/type",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_a/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_a/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_a/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_b/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_b/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_b/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_c/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_c/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_c/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_d/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_d/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_d/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_e/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_e/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_e/3",
"/graviteeio/apim/gateway/management/datasource/config/default/connectionsPerHost",
"/graviteeio/apim/gateway/management/datasource/config/default/connectTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/cursorFinalizerEnabled",
"/graviteeio/apim/gateway/management/datasource/config/default/dbname",
"/graviteeio/apim/gateway/management/datasource/config/default/host",
"/graviteeio/apim/gateway/management/datasource/config/default/password",
"/graviteeio/apim/gateway/management/datasource/config/default/port",
"/graviteeio/apim/gateway/management/datasource/config/default/username",
"/graviteeio/apim/gateway/management/datasource/config/default/description",
"/graviteeio/apim/gateway/management/datasource/config/default/heartbeatConnectTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/heartbeatFrequency",
"/graviteeio/apim/gateway/management/datasource/config/default/heartbeatSocketTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/localThreshold",
"/graviteeio/apim/gateway/management/datasource/config/default/maxConnectionIdleTime",
"/graviteeio/apim/gateway/management/datasource/config/default/maxConnectionLifeTime",
"/graviteeio/apim/gateway/management/datasource/config/default/maxWaitTime",
"/graviteeio/apim/gateway/management/datasource/config/default/minConnectionsPerHost",
"/graviteeio/apim/gateway/management/datasource/config/default/minHeartbeatFrequency",
"/graviteeio/apim/gateway/management/datasource/config/default/serverSelectionTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/socketKeepAlive",
"/graviteeio/apim/gateway/management/datasource/config/default/socketTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/sslEnabled",
"/graviteeio/apim/gateway/management/datasource/config/default/threadsAllowedToBlockForConnectionMultiplier",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_a/uri",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_b/uri",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_c/uri",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_d/uri",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_e/uri",
"/graviteeio/apim/gateway/reporters/elasticsearch/cluster",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_a/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_a/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_a/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_b/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_b/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_b/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_c/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_c/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_c/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_d/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_d/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_d/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_e/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_e/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_e/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/type",
"/graviteeio/apim/gateway/reporters/elasticsearch/index",
"/graviteeio/apim/gateway/reporters/elasticsearch/security/username",
"/graviteeio/apim/gateway/reporters/elasticsearch/security/password",
"/graviteeio/apim/management/analytics/elasticsearch/settings/number_of_replicas",
"/graviteeio/apim/management/analytics/elasticsearch/settings/number_of_shards",
"/graviteeio/apim/management/http/cors/allow-methods",
"/graviteeio/apim/management/http/cors/allow-origin",
"/graviteeio/apim/management/http/cors/max-age",
"/graviteeio/apim/management/http/customize",
"/graviteeio/apim/management/jetty/acceptors",
"/graviteeio/apim/management/jetty/accesslog/enable",
"/graviteeio/apim/management/jetty/accesslog/path",
"/graviteeio/apim/management/jetty/customize",
"/graviteeio/apim/management/jetty/host",
"/graviteeio/apim/management/jetty/idleTimeout",
"/graviteeio/apim/management/jetty/jmx",
"/graviteeio/apim/management/jetty/pool/idleTimeout",
"/graviteeio/apim/management/jetty/pool/maxThreads",
"/graviteeio/apim/management/jetty/pool/minThreads",
"/graviteeio/apim/management/jetty/pool/queueSize",
"/graviteeio/apim/management/jetty/selectors",
"/graviteeio/apim/management/jetty/statistics",
"/graviteeio/apim/management/plugins/customize",
"/graviteeio/apim/management/plugins/failOnDuplicate",
"/graviteeio/apim/management/plugins/path/custom",
"/graviteeio/apim/management/plugins/path/generic",
"/graviteeio/apim/management/security/providers/type/gravitee/enable",
"/graviteeio/apim/management/security/providers/type/ldap/context-source-base",
"/graviteeio/apim/management/security/providers/type/ldap/context-source-password",
"/graviteeio/apim/management/security/providers/type/ldap/context-source-url",
"/graviteeio/apim/management/security/providers/type/ldap/context-source-username",
"/graviteeio/apim/management/security/providers/type/ldap/enable",
"/graviteeio/apim/management/security/providers/type/ldap/group-role-attribute",
"/graviteeio/apim/management/security/providers/type/ldap/group-search-base",
"/graviteeio/apim/management/security/providers/type/ldap/role-mapper",
"/graviteeio/apim/management/security/providers/type/ldap/user-dn-patterns",
"/graviteeio/apim/management/security/providers/type/ldap/user-search-base",
"/graviteeio/apim/management/security/providers/type/ldap/user-search-filter",
"/graviteeio/apim/management/security/providers/type/ldap/user-search-objectclass",
"/graviteeio/apim/management/security/providers/type/memory/enable",
"/graviteeio/apim/management/security/providers/type/memory/password-encoding-algo",
"/graviteeio/apim/management/security/providers/type/memory/users/1",
"/graviteeio/apim/management/security/providers/type/memory/users/2",
"/graviteeio/apim/management/security/providers/type/memory/users/3",
"/graviteeio/apim/management/security/providers/type/memory/users/4",
"/graviteeio/apim/management/security/providers/type/memory/users/5",
"/graviteeio/apim/management/security/providers/type/memory/users/6",
"/graviteeio/apim/management/security/providers/type/memory/users/7",
"/graviteeio/apim/management/security/providers/type/memory/users/8",
"/graviteeio/apim/management/security/providers/type/memory/users/9",
"/graviteeio/apim/management/security/providers/type/memory/users/10",
"/graviteeio/apim/management/services/core/http/authentication/type",
"/graviteeio/apim/management/services/core/http/authentication/users/password",
"/graviteeio/apim/management/services/core/http/enable",
"/graviteeio/apim/management/services/core/http/host",
"/graviteeio/apim/management/services/core/http/port"
]
