version: '2'
services:
  mongos-router:
    environment:
      ENVIRONMENT: ${environment_prefix}
      BACKEND_NODE: ${consul_uri}
      CONFIG_MODE: consul
      TARGET_DC: ${dc}
    ports:
      - 27017:27017/tcp
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
    image: registry.adeo.com/sly/mongos-router:1.0.0-SNAPSHOT
    stdin_open: true
    
  gravitee-gateway:
    environment:
      ENVIRONMENT: ${environment_prefix}
      BACKEND_NODE: ${consul_uri}
      CONFIG_MODE: consul
      TARGET_DC: ${dc}
      MONGOS_CLI: true
      TENANT: ${tenant}
      SHARDING_TAGS: ${sharding_tags}
    ports:
      - 8082:8082/tcp
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
    image: registry.adeo.com/sly/gravitee-gateway:1.0.0-SNAPSHOT
    stdin_open: true
