version: '2'
services:
  webapp:
    environment:
      ENVIRONMENT: ${environment_prefix}
      BACKEND_NODE: ${consul_uri}
      CONFIG_MODE: consul
      MONGOS_CLI: ${mongos_enable}
      TARGET_DC: ${dc}
    ports:
      - 8083:8083/tcp
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
    image: registry.adeo.com/sly/gravitee-management-api:1.0.0-SNAPSHOT
    stdin_open: true
