[template]
src = "gravitee.yml.tmpl"
dest = "/opt/graviteeio-gateway-1.13.2/config/gravitee.yml"
keys = [ 
"/graviteeio/apim/gateway/cache/type",
"/graviteeio/apim/gateway/handlers/request/transaction/header",
"/graviteeio/apim/gateway/http/alpn",
"/graviteeio/apim/gateway/http/compressionSupported",
"/graviteeio/apim/gateway/http/customize",
"/graviteeio/apim/gateway/http/host",
"/graviteeio/apim/gateway/http/idleTimeout",
"/graviteeio/apim/gateway/http/instances",
"/graviteeio/apim/gateway/http/port",
"/graviteeio/apim/gateway/http/secured",
"/graviteeio/apim/gateway/http/ssl/clientAuth",
"/graviteeio/apim/gateway/http/ssl/customize",
"/graviteeio/apim/gateway/http/ssl/keystore/path",
"/graviteeio/apim/gateway/http/ssl/keystore/secret",
"/graviteeio/apim/gateway/http/ssl/truststore/path",
"/graviteeio/apim/gateway/http/ssl/truststore/secret",
"/graviteeio/apim/gateway/http/tcpKeepAlive",
"/graviteeio/apim/gateway/management/datasource/config/type",
"/graviteeio/apim/gateway/management/datasource/type",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_a/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_a/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_a/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_b/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_b/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_b/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_c/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_c/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_c/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_d/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_d/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_d/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_e/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_e/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/dc_e/3",
"/graviteeio/apim/gateway/management/datasource/config/default/connectionsPerHost",
"/graviteeio/apim/gateway/management/datasource/config/default/connectTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/cursorFinalizerEnabled",
"/graviteeio/apim/gateway/management/datasource/config/default/dbname",
"/graviteeio/apim/gateway/management/datasource/config/default/host",
"/graviteeio/apim/gateway/management/datasource/config/default/password",
"/graviteeio/apim/gateway/management/datasource/config/default/port",
"/graviteeio/apim/gateway/management/datasource/config/default/username",
"/graviteeio/apim/gateway/management/datasource/config/default/description",
"/graviteeio/apim/gateway/management/datasource/config/default/heartbeatConnectTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/heartbeatFrequency",
"/graviteeio/apim/gateway/management/datasource/config/default/heartbeatSocketTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/localThreshold",
"/graviteeio/apim/gateway/management/datasource/config/default/maxConnectionIdleTime",
"/graviteeio/apim/gateway/management/datasource/config/default/maxConnectionLifeTime",
"/graviteeio/apim/gateway/management/datasource/config/default/maxWaitTime",
"/graviteeio/apim/gateway/management/datasource/config/default/minConnectionsPerHost",
"/graviteeio/apim/gateway/management/datasource/config/default/minHeartbeatFrequency",
"/graviteeio/apim/gateway/management/datasource/config/default/serverSelectionTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/socketKeepAlive",
"/graviteeio/apim/gateway/management/datasource/config/default/socketTimeout",
"/graviteeio/apim/gateway/management/datasource/config/default/sslEnabled",
"/graviteeio/apim/gateway/management/datasource/config/default/threadsAllowedToBlockForConnectionMultiplier",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_a/uri",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_b/uri",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_c/uri",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_d/uri",
"/graviteeio/apim/gateway/management/mongo/config/uri/dc_e/uri",
"/graviteeio/apim/gateway/plugins/customize",
"/graviteeio/apim/gateway/plugins/failOnDuplicate",
"/graviteeio/apim/gateway/plugins/path/custom",
"/graviteeio/apim/gateway/plugins/path/generic",
"/graviteeio/apim/gateway/policy/api-key/header",
"/graviteeio/apim/gateway/policy/api-key/param",
"/graviteeio/apim/gateway/policy/customize",
"/graviteeio/apim/gateway/ratelimit/mongo/uri",
"/graviteeio/apim/gateway/reporters/list/1",
"/graviteeio/apim/gateway/reporters/list/2",
"/graviteeio/apim/gateway/reporters/list/3",
"/graviteeio/apim/gateway/reporters/elasticsearch",
"/graviteeio/apim/gateway/reporters/cloudwatch",
"/graviteeio/apim/gateway/reporters/cloudwatch/enabled",
"/graviteeio/apim/gateway/reporters/config/customize",
"/graviteeio/apim/gateway/reporters/elasticsearch/bulk/actions",
"/graviteeio/apim/gateway/reporters/elasticsearch/bulk/conccurent_requests",
"/graviteeio/apim/gateway/reporters/elasticsearch/bulk/flush_interval",
"/graviteeio/apim/gateway/reporters/elasticsearch/cluster",
"/graviteeio/apim/gateway/reporters/elasticsearch/enabled",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_a/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_a/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_a/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_b/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_b/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_b/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_c/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_c/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_c/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_d/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_d/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_d/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_e/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_e/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/dc_e/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/type",
"/graviteeio/apim/gateway/reporters/elasticsearch/index",
"/graviteeio/apim/gateway/reporters/elasticsearch/security/username",
"/graviteeio/apim/gateway/reporters/elasticsearch/security/password",
"/graviteeio/apim/gateway/reporters/elasticsearch/pipeline/plugins/ingest",
"/graviteeio/apim/gateway/reporters/elasticsearch/settings/number_of_replicas",
"/graviteeio/apim/gateway/reporters/elasticsearch/settings/number_of_shards",
"/graviteeio/apim/gateway/reporters/system/buffersize",
"/graviteeio/apim/gateway/services/apikeyscache/delay",
"/graviteeio/apim/gateway/services/apikeyscache/threads",
"/graviteeio/apim/gateway/services/apikeyscache/unit",
"/graviteeio/apim/gateway/services/cloudwatch/dashboardName",
"/graviteeio/apim/gateway/services/cloudwatch/enabled",
"/graviteeio/apim/gateway/services/core/http/authentication/type",
"/graviteeio/apim/gateway/services/core/http/authentication/users/admin",
"/graviteeio/apim/gateway/services/core/http/enabled",
"/graviteeio/apim/gateway/services/core/http/host",
"/graviteeio/apim/gateway/services/core/http/port",
"/graviteeio/apim/gateway/services/local/enabled",
"/graviteeio/apim/gateway/services/local/path",
"/graviteeio/apim/gateway/services/monitoring/delay",
"/graviteeio/apim/gateway/services/monitoring/unit",
"/graviteeio/apim/gateway/services/sync/cron",
"/graviteeio/apim/gateway/tags",
"/graviteeio/apim/gateway/tenant"
]
